// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPf0fZxqpLe3aWOaH4lrdubrxZn0ahC7Q',
    appId: '1:843320279296:web:d07a0e42690963094b33e5',
    messagingSenderId: '843320279296',
    projectId: 'kiady-42e8c',
    authDomain: 'kiady-42e8c.firebaseapp.com',
    storageBucket: 'kiady-42e8c.appspot.com',
    measurementId: 'G-PQT6WTPJ19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWmIugRCEAb0kEaZO0EefJv6HZYIN_AI',
    appId: '1:843320279296:android:24c88b97bd4753464b33e5',
    messagingSenderId: '843320279296',
    projectId: 'kiady-42e8c',
    storageBucket: 'kiady-42e8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5-RjgkeKiZU0PaAezixcRrF579UmYU3I',
    appId: '1:843320279296:ios:b4d54e39cf3fb6b34b33e5',
    messagingSenderId: '843320279296',
    projectId: 'kiady-42e8c',
    storageBucket: 'kiady-42e8c.appspot.com',
    androidClientId: '843320279296-aejn2lv1jv7hp6mg3otmlkhch6a5t22r.apps.googleusercontent.com',
    iosClientId: '843320279296-in8hsg60fgc9lce7is0mai88ovchbmk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.personnalCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5-RjgkeKiZU0PaAezixcRrF579UmYU3I',
    appId: '1:843320279296:ios:b4d54e39cf3fb6b34b33e5',
    messagingSenderId: '843320279296',
    projectId: 'kiady-42e8c',
    storageBucket: 'kiady-42e8c.appspot.com',
    androidClientId: '843320279296-aejn2lv1jv7hp6mg3otmlkhch6a5t22r.apps.googleusercontent.com',
    iosClientId: '843320279296-in8hsg60fgc9lce7is0mai88ovchbmk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.personnalCalendar',
  );
}
